### ISSUE TITLE
Move modules to Jekyll collections

### ISSUE THREAD

**Issue by robdy** [get-itips/msshells#24]
As we talked via Twitter, modules could be moved to [collections](https://jekyllrb.com/docs/collections/) so that the data is better organized.

Opening an issue so we don't forget about it :)

**Comment by get-itips** [comment]
> As we talked via Twitter, modules could be moved to [collections](https://jekyllrb.com/docs/collections/) so that the data is better organized.
> 
> Opening an issue so we don't forget about it :)

Great! will take a look a the doc you shared here. Thanks
