### ISSUE TITLE
SharePoint PNP PowerShell

### ISSUE THREAD

**Issue by Shoehorner** [get-itips/msshells#281]
Hello,

I love the site as it helps me get setup on a new PC for connecting and managing Azure and M365. One module that I did notice was missing that would be a nice addition is the SharePoint PNP module.

https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets

**Comment by get-itips** [comment]
Hello @Shoehorner Shaun, thanks for your feedback, I appreciate it a lot!
Yes! PnP is a great module, however, it's not official as it is a community driven effort... let me think about a way I can include it under another category or something similar
